name: Build Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  update-manifest:
    runs-on: ['self-hosted', 'Linux', 'X64']
    name: Update-Manifest
    needs: docker-build
    steps:
      - uses: actions/checkout@v2

      - name: Write Manifest
        env:
          DOCKERHUB: ${{ secrets.DOCKERHUB }}
        run: |
          export DOCKER_CONFIG=$HOME/.docker
          echo $DOCKERHUB | docker login -u fastandfearless --password-stdin
          jq '.experimental = "enabled"' < $DOCKER_CONFIG/config.json > $DOCKER_CONFIG/config.json.new
          #cat $DOCKER_CONFIG/config.json.new
          mv $DOCKER_CONFIG/config.json.new $DOCKER_CONFIG/config.json
          GITCOMMIT=$(git rev-parse --short HEAD)
          docker manifest create fastandfearless/developers-paradise:$GITCOMMIT \
            fastandfearless/developers-paradise:$GITCOMMIT-amd64 \
            fastandfearless/developers-paradise:$GITCOMMIT-arm \
            fastandfearless/developers-paradise:$GITCOMMIT-arm64
          docker manifest annotate fastandfearless/developers-paradise:$GITCOMMIT \
             fastandfearless/developers-paradise:$GITCOMMIT-amd64 --os linux --arch amd64
          docker manifest annotate fastandfearless/developers-paradise:$GITCOMMIT \
             fastandfearless/developers-paradise:$GITCOMMIT-arm --os linux --arch arm --variant v7
          docker manifest annotate fastandfearless/developers-paradise:$GITCOMMIT \
             fastandfearless/developers-paradise:$GITCOMMIT-arm64 --os linux --arch arm64 --variant v8
          docker manifest push fastandfearless/developers-paradise:$GITCOMMIT

          docker tag fastandfearless/developers-paradise:$GITCOMMIT-amd64 fastandfearless/developers-paradise:latest-amd64
          docker tag fastandfearless/developers-paradise:$GITCOMMIT-arm64 fastandfearless/developers-paradise:latest-arm64
          docker tag fastandfearless/developers-paradise:$GITCOMMIT-arm fastandfearless/developers-paradise:latest-arm
          docker push fastandfearless/developers-paradise:latest-amd64
          docker push fastandfearless/developers-paradise:latest-arm64
          docker push fastandfearless/developers-paradise:latest-arm

          docker manifest create fastandfearless/developers-paradise:latest \
            fastandfearless/developers-paradise:latest-amd64 \
            fastandfearless/developers-paradise:latest-arm \
            fastandfearless/developers-paradise:latest-arm64
          docker manifest push fastandfearless/developers-paradise:latest

  docker-build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: ['self-hosted', 'Linux', 'ARM64']
            arch: arm64
          - platform: ['self-hosted', 'Linux', 'ARM']
            arch: arm
          - platform: ['self-hosted', 'Linux', 'X64']
            arch: amd64

    name: Build Docker ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker
        env:
          DOCKERHUB: ${{ secrets.DOCKERHUB }}
        run: |
          echo $DOCKERHUB | docker login -u fastandfearless --password-stdin
          GITCOMMIT=$(git rev-parse --short HEAD)
          docker build . --tag fastandfearless/developers-paradise:${GITCOMMIT}-${{ matrix.arch }}
          docker push fastandfearless/developers-paradise:${GITCOMMIT}-${{ matrix.arch }}


